### PR TITLE
Fix possible typo in androidFilePwd command and keep typo version for compatibility

### PR DESCRIPTION
**Pull request by root-intruder**
the rpc call androidFileCwd should be called andoidFilePwd, since it also calls the pwd function!?

### CODE REVIEW

**Comment by leonjza** [comment]
Hey, I am not 100% certain where this typo is coming from? Could you help me understand?

**Comment by root-intruder** [comment]
CWD stands for change working directory. however as you can see in the changelog of my commit, it calls the android pwd command which prints the working directory,,,and that is also what it does. 

However, I also saw the CWD used in frida...don't remember where exactly. It could come from there.

however, the executed function is definetly PWD which should also be the name

**Comment by leonjza** [comment]
The Python side calls the correct RPC method [here](https://github.com/sensepost/objection/blob/1.9.6/objection/commands/filemanager.py#L201).

Thanks!

**Comment by root-intruder** [comment]
mybe cwd was translated with current working directory....but coming from linux it stands for somethong else

**Pull request closed without merging**
