### PR TITLE
Android: adding ability to support wildcards in class names during hooking

### LINKED ISSUE #150: [Feature Request] Android watch class wildcard
Similar to issue #45 , but instead of methods, being able to monitor all methods in classes that match a wildcard regex, for example:

`android hooking watch class 'com.exampleapp.ui.login.*' --dump-args --dump-return`

Is this useful? If so I can have a PR ready...

### PR DESCRIPTION
**Pull request by dvas0004**
Fixes #150. This commit will allow users to issue commands similar to:

`android hooking watch class 'com.example.ui.*' --dump-args --dump-return`

Some notes:
- Only wildcard '*'  as shown above is supported. No regex support at the moment
- Usage remains the same as before, and testing so far showed no issues, though it's worth highlighting to users that hooking into many classes at once (especially with `--dump-backtrace` enabled) will produce quite a load and can cause lack of responsiveness or app crashes

This commit still supports previous command invocations including the whole class name, e.g.:

`android hooking watch class 'com.example.ui.LoginActivity' --dump-args --dump-return`

### CODE REVIEW

**Comment by leonjza** [comment]
Thanks! 🙌Will test this asap.
Just a heads up, I'll probably port this to TypeScript when the Android hooks for the new agent takes shape though.

**Comment by dvas0004** [comment]
That's awesome. If you need some help with typescript delegate something to
me will definitely submit a PR to help out

**Comment by leonjza** [comment]
I just merged the TypeScript agent port. Could you perhaps update this PR for that? Apologies for the extra effort because of this now!

**Comment by leonjza** [comment]
Just realised this targets the old typescript_agent branch. Could we also do this for master instead now? Thanks again!

**Pull request closed without merging**
