### PR TITLE
Fix #165. and other bugs

### LINKED ISSUE #165: Wrong directory separator with cd and upload/download from Windows host
For `cd`, this appears to be due to:
https://github.com/sensepost/objection/blob/e7f0a22291a65a58af7e409f2ea8c891731d4dac/objection/commands/filemanager.py#L93

Similarly, for `file download` and `file upload`:
https://github.com/sensepost/objection/blob/e7f0a22291a65a58af7e409f2ea8c891731d4dac/objection/commands/filemanager.py#L481
https://github.com/sensepost/objection/blob/e7f0a22291a65a58af7e409f2ea8c891731d4dac/objection/commands/filemanager.py#L547
https://github.com/sensepost/objection/blob/e7f0a22291a65a58af7e409f2ea8c891731d4dac/objection/commands/filemanager.py#L619

`os.path.join` will use the path separator of the _host_ device, not the client - if using a Windows host, this will use `\`, not `/`.

This is only used with Android and iOS devices, so using a forward slash should be sufficient.

### PR DESCRIPTION
**Pull request by JBalanza**
Hi!

I did not found any PR policy so swear i'm not doing wrong.
Here are two commits for two bugs:

    The first is related with issue #165. As os.path.join were used in filemanager.py, when running on Windows it join the strings with Windows separator "". As these paths are applied to frida environment running on Android or iOS, they uses Posix separators, so always "/" is used then.
    The second is when a path contains ".." (in example: "../cache"). After accessing it (succesfull) the code stores the same string (with the ".." not resolved) on the "file_manager_state.cwd" so following actions involving paths will fail.

Regards,
Javier.

### CODE REVIEW

**Comment by leonjza** [comment]
Thanks for the PR! 

@JBalanza & @aph3rson could we target the [`typescript_agent`](https://github.com/sensepost/objection/tree/typescript_agent) branch for this as I am close to wrapping things up there and merging that into master.

**Comment by JBalanza** [comment]
The error returned by Travis-CI I cannot figure out why it is produced despite I edited the source code in Windows environment. I'm pretty sure the changes wouln't fail the test. But they failed.
Anyway, I separate the PR in three commits, so If you want you can only merge the first one that passes all the test. Should I then PR into the typescript_agent branch?

**Comment by aph3rson** [comment]
@JBalanza CI didn't run on ab33a21, as it was pushed at the same time as 40a7413. You didn't make any changes to that portion of the code, and it's failing on a match for an intermediate status. It might be prudent to have a contributor re-run CI on `master`, and see if it's an upstream change with one of our requirements.

@leonjza looking at the blame and a diff, these changes should be compatible with a merge from `typescript_agent`.

**Comment by JBalanza** [comment]
There is something then I could do by my side for integrating those commits into any branch?

**Comment by leonjza** [comment]
The `typescript_agent` branch is going to be merged *very* soon (like probably today soon), so don't worry about that now. Once it's merged lets land these bug fixes too.

Thanks for your patience!

**Comment by leonjza** [comment]
I have merged the branch, but it looks like there is some minor merge conflicts to solve before I can merge this PR.

**Comment by JBalanza** [comment]
With pleasure I will pull a fresh copy of the master-branch and review my code. Also i'm going to separate the Two main commits here into 2 PR so we can handle them better.

**Comment by leonjza** [comment]
Awesome. I'll close the PR then and continue on the new ones when you create 'em. Thanks!

**Pull request closed without merging**
