### PR TITLE
Added: android ui screenshot

### PR DESCRIPTION
**Pull request by bernard-wagner**
# Description #

Loops through Activities and finds the first one not in a paused state. Thereafter dumps the drawing cache of the Activity. Works even when FLAG_SECURE is set.

# Example # 

```
ubuntu@ubuntu-dev:~/workspace/objection$ python3 -m objection.console.cli --gadget jakhar.aseem.diva explore

     _     _         _   _
 ___| |_  |_|___ ___| |_|_|___ ___
| . | . | | | -_|  _|  _| | . |   |
|___|___|_| |___|___|_| |_|___|_|_|
        |___|(object)inject(ion) v1.0.2

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
GT-I9500 on (samsung: 5.0.1) [usb] # android ui screenshot /tmp/test.png
Screenshot saved to: /tmp/test.png
```

# Known issues #
* Doesn't screenshot correctly if a dialog is in the foreground.
* Base64 encoding of byte[] should not be necessary, but ran into problems using get_extra_data and raw byte[]

### CODE REVIEW

**Comment by leonjza** [comment]
Thanks! This is too cool 😎 

I played around with a few apps to test this with, and noticed that taking a screenshot of [this](https://github.com/CyberScions/Digitalbank) applications home page seems to timeout when Base64 encoding the image to `send()` to the python environment. I am not 100% sure why yet, but this had me thinking:

- Is there a faster way to get the foregrounded activity instead of a `filter()` on them all? I think this approach will chomp precious seconds in large applications with many activities.
- We don't have a lot of time in the hook itself and need to finish pretty fast or else Frida will go all `frida.TransportError: timeout was reached` on us. Does it make sense to maybe make use of an RPC exported function here?
- What was the problem you were facing with [`get_extra_data()`](https://github.com/sensepost/objection/blob/master/objection/utils/frida_transport.py#L56)?

**Comment by bernard-wagner** [comment]
Will need to play around with filter() alternatives. ES5 doesn't support .find() which would have been ideal, but we can always just do a for loop with a break. Might be worth doing it in reverse order, depending on how the activity stack grows. However, I don't think this is where the bottleneck is introduced. Will do some analysis and try and eliminate the cause of the delay. 

Can definitely use an RPC exported function to fetch the result if the delay is unavoidable.

Klapped out the code in 30 minutes, so definitely just noobing out with Memory.readByteArray and how to send it so that get_extra_data doesn't complain about encoding etc.

Will see if I can get around to the improvements over the weekend.

**Comment by bernard-wagner** [comment]
Had a bit of time to run some profiling on the script.

The bottleneck is ByteArrayOutputStream.toByteArray() and is kind of unavoidable, unless we can stream data. No idea why getWindow().getDecorView().getRootView() is so slow.

t1(getCurrentActivity):26
t2(getRootView):551
t3(getDrawingCache):159
t4(Bitmap.compress):1540
t5(ByteArrayOutputStream.toByteArray):20739

**Comment by bernard-wagner** [comment]
Rewrote the module to use rpc.exports. Still extremely slow for DigitalBank. Screenshot is 1 MB.

**Comment by leonjza** [comment]
Awesome! Ill merge this as soon as possible.

**Comment by leonjza** [comment]
> Rewrote the module to use rpc.exports. Still extremely slow for DigitalBank. Screenshot is 1 MB.

Yeah even though it takes some time, taking the screenshot completes now. Thanks again!

**Pull request merged**
