### PR TITLE
Support for apktool d --only-main-classes

### LINKED ISSUE #659: Support for apktool d --only-main-classes
**Is your feature request related to a problem? Please describe.**
Some apps can't be properly build into an APK when they are not decoded with `apktool d --only-main-classes`, see https://github.com/iBotPeaches/Apktool/issues/2784

**Describe the solution you'd like**
Add an option to use `--only-main-classes` when decoding

**Describe alternatives you've considered**
Changing the source manually.

**Additional context**
https://github.com/ax/apk.sh/issues/30

### PR DESCRIPTION
**Pull request by AltayAkkus**
Fixes #659

### CODE REVIEW

**Comment by AltayAkkus** [comment]
@leonjza what do you think?

**Comment by leonjza** [comment]
Implementation looks good. Sorry I haven't merged yet; I don't have a lot of bandwidth to spare at the moment.

**Comment by IrvanWijayaSardam** [comment]
when this one is gonna get merged ? or how do i use it rn ?

**Comment by leonjza** [comment]
Thanks!

**Comment by AltayAkkus** [comment]
Thanks for the merge!

**Pull request merged**
