### PR TITLE
temporal fix for download file in android

### PR DESCRIPTION
**Pull request by dalgarins**
this is my temporal fix for issue; https://github.com/sensepost/objection/issues/92

when you try to download a file from apk in a non-root android device.

### CODE REVIEW

**Comment by leonjza** [comment]
Thanks for the PR! It should be noted that `java.nio.file.Files` is only available in API level 26 and up, meaning one would need at least Android 8.0 for this to work.

**Comment by dalgarins** [comment]
yes, this is a temporal solution, I have tested only in Android 8.0, If you want you can share your idea about the real issue, I would like to help you coding in this framework, I like objection.

**Comment by leonjza** [comment]
Awesome 👍 
I have picked up where I left off last year with the TypeScript agent port, and hope to have this done pretty soon! The way [files are read](https://github.com/sensepost/objection/blob/typescript_agent/agent/src/android/filesystem.ts#L76-L79) there will be compatible with any Android version.

**Comment by leonjza** [comment]
This should be solved in the next release! Thanks for the PR!

**Pull request closed without merging**
